name: keepalive

on:
  schedule:
    # Cada 15 minutos (UTC). Ajusta si quieres más/menos.
    - cron: "*/15 * * * *"
  workflow_dispatch: {}  # permite lanzarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: keepalive
      cancel-in-progress: false
    steps:
      - name: Curl app
        run: |
          URL="https://acidsmart-jatatddk6nywvatvsafoiz.streamlit.app/"
          echo "Pinging $URL ..."
          # 3 reintentos, 10s timeout, imprime HTTP code
          for i in 1 2 3; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              --max-time 10 \
              -H "Cache-Control: no-cache" \
              -H "Pragma: no-cache" \
              -A "keepalive-bot/1.0" \
              "$URL") || true
            echo "Attempt $i -> HTTP $CODE"
            if [ "$CODE" = "200" ] || [ "$CODE" = "304" ]; then
              exit 0
            fi
            sleep 10
          done
          echo "App did not return 200/304"
          exit 1
